config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  get "/tasks", to: "tasks#index", as: :tasks
  # Create
  get "/tasks/new", to: "tasks#new", as: :new_task
  post "/tasks", to: "tasks#create"
  # Read one
  get "/tasks/:id", to: "tasks#show", as: :task
  # Update
  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "/tasks/:id", to: "tasks#update"
  # Delete
  delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/show.html.erb
<div><ul>
<li><%= @task.title %></li>
<li><%= @task.details %></li>
<li><% if @task.completed = false %>
    <p>[X] This task is not completed.</p>
  <% elsif @task.completed = true %>
    <p>[ ] This task is not completed.</p>
<% end %></li>
</ul></div>

<div><%= link_to "Back to list", tasks_path %></div>

app/views/tasks/create.html.erb
<form_with>
</form_with>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit "Update" %>
<% end %>

<div>
<% if @task.completed = true %>
  <p>[X] Completed </p>
<% elsif @task.completed = false %>
  <p>[ ] Completed </p>
<% end %>
</div>

<div>
<%= link_to "Back to list", tasks_path %>
  <i class="fa-solid fa-rotate-left"></i>
</div>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %>
      <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to new_task_path do %>
    <i class="fa-solid fa-plus"></i> Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<div>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/tasks/show.html.erb
<h1>Task details</h1>

<div>
<%= link_to "Edit this task", task_edit_path(@task), class: "btn btn-primary mt-3" %>
</div>

<div><ul>
<li><%= @task.title %></li>
<li><%= @task.details %></li>
<li><% if @task.completed = false %>
  <i class="fa-regular fa-square-check"></i> Completed
  <% elsif @task.completed = true %>
  <i class="fa-regular fa-square"></i> Completed
<% end %></li>
</ul></div>

<div>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-rotate-left"></i> Back to list
  <% end %>
</div>